name: Docker Build and Push

on:
  push:
    # branches: [ "main" ]
  workflow_dispatch:
    inputs:
      manual_version:
        description: 'ম্যানুয়াল ভার্সন (যেমন v1.0)'
        required: false
        default: ''

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            woodcraftbot/1tamilmv-bot:latest
            woodcraftbot/1tamilmv-bot:${{ github.sha }}
            woodcraftbot/1tamilmv-bot:v1.0
            ${{ github.event.inputs.manual_version && format('woodcraftbot/1tamilmv-bot:{0}', github.event.inputs.manual_version) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
